[package]
name = "gainsnap"
version = "0.1.0"
edition = "2021"
publish = false
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["radiant-gui"]
radiant-gui = ["toybox/radiant-gui", "dep:radiant"]
vst3 = ["toybox/radiant-vst3", "radiant-gui"]
screenshot-test = ["dep:image", "radiant-gui"]

[dependencies]
toybox = { git = "https://github.com/PORTALSURFER/toybox.git", rev = "e0090c1debf1bae9156e57415085b170cc35ee90", default-features = false }
radiant = { git = "https://github.com/PORTALSURFER/radiant.git", rev = "7001b84b2c7edd4a286d167c183a5b35366156fc", default-features = false, optional = true }
image = { version = "0.25", default-features = false, features = ["png"], optional = true }

[build-dependencies]
toybox = { git = "https://github.com/PORTALSURFER/toybox.git", rev = "e0090c1debf1bae9156e57415085b170cc35ee90", default-features = false }

[target.'cfg(target_os = "windows")'.dev-dependencies]
windows = { version = "0.62", default-features = false, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }

[lints.rust]
warnings = "deny"

[lints.rustdoc]
missing_crate_level_docs = "deny"
